version: '2'

services:
  limedb:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: limesurvey
      MYSQL_USER: limesurvey
      MYSQL_PASSWORD: limesurveypwd

  limeapp:
    depends_on:
      - limedb
    image: amontaigu/limesurvey:latest
    restart: always
    volumes:
      - www_data:/var/www
      - fpm_sock:/var/run/php

  limefront:
    depends_on:
      - limeapp
    image: amontaigu/nginx:1.13.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - www_data:/var/www
      - fpm_sock:/var/run/php

volumes:
  db_data:
  www_data:
  fpm_sock: